name: Merge DEV into PROD

on:
  push:
    branches:
      - DEV

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: DEV

    - name: Fetch origin
      run: |
        git remote set-url origin https://github.com/furqankaka11/assignment.git:${ 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 }@github.com/assignment.git
        git fetch origin

    - name: Checkout PROD branch
      run: |
        git checkout PROD
        git pull origin PROD

    - name: Merge DEV into PROD
      run: |
        git merge DEV
        git push origin PROD
